# rule identifiers to exclude from running
disabled_rules:
- trailing_whitespace
- vertical_whitespace
- void_return
- trailing_newline
- vertical_parameter_alignment
- implicit_getter
- redundant_string_enum_value
- todo #Temporary

# paths to ignore during linting. Takes precedence over `included`.
excluded:
- Pods

# custom rules and overrides
identifier_name:
 min_length: # only min_length
  error: 3 # only error
 excluded: # excluded via string array
  - id
  - URL
  - url
  - GlobalAPIKey
  - i
  - j
  - me

line_length: 190
cyclomatic_complexity: 20

attributes:
 always_on_same_line: ["@IBAction", "@IBOutlet"]
 always_on_line_above: ["@IBInspectable", "@UIApplicationMain", "@discardableResult", "@objc"]
